import { NavigationItem } from "../types";

export const navigationData: NavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: "home",
    children: [
      {
        id: "dashboard-analysis",
        title: "Analysis",
        path: "/",
        icon: "arrow_right",
      },
      {
        id: "dashboard-ecommerce",
        title: "eCommerce",
        path: "/dashboard/ecommerce",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "widgets",
    title: "Widgets",
    icon: "widgets",
    children: [
      {
        id: "widgets-data",
        title: "Data",
        path: "/widgets/data",
        icon: "arrow_right",
      },
      {
        id: "widgets-static",
        title: "Static",
        path: "/widgets/static",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "apps",
    title: "Apps",
    icon: "apps",
    children: [
      {
        id: "apps-email",
        title: "Email Box",
        path: "/apps/email",
        icon: "arrow_right",
      },
      {
        id: "apps-email-read",
        title: "Email Read",
        path: "/apps/email-read",
        icon: "arrow_right",
      },
      {
        id: "apps-chat",
        title: "Chat",
        path: "/apps/chat",
        icon: "arrow_right",
      },
      {
        id: "apps-calendar",
        title: "Calendar",
        path: "/apps/calendar",
        icon: "arrow_right",
      },
      {
        id: "apps-todo",
        title: "To do",
        path: "/apps/todo",
        icon: "arrow_right",
      },
      {
        id: "apps-invoice",
        title: "Invoice",
        path: "/apps/invoice",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "ui-elements-label",
    title: "UI Elements",
    icon: undefined,
    children: [],
  },
  {
    id: "cards",
    title: "Cards",
    icon: "inventory_2",
    path: "/cards",
  },
  {
    id: "ecommerce",
    title: "eCommerce",
    icon: "shopping_bag",
    children: [
      {
        id: "ecommerce-add-product",
        title: "Add Product",
        path: "/ecommerce/add-product",
        icon: "arrow_right",
      },
      {
        id: "ecommerce-products",
        title: "Products",
        path: "/ecommerce/products",
        icon: "arrow_right",
      },
      {
        id: "ecommerce-customers",
        title: "Customers",
        path: "/ecommerce/customers",
        icon: "arrow_right",
      },
      {
        id: "ecommerce-customer-details",
        title: "Customer Details",
        path: "/ecommerce/customer-details",
        icon: "arrow_right",
      },
      {
        id: "ecommerce-orders",
        title: "Orders",
        path: "/ecommerce/orders",
        icon: "arrow_right",
      },
      {
        id: "ecommerce-order-details",
        title: "Order Details",
        path: "/ecommerce/order-details",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "components",
    title: "Components",
    icon: "card_giftcard",
    children: [
      {
        id: "components-alerts",
        title: "Alerts",
        path: "/components/alerts",
        icon: "arrow_right",
      },
      {
        id: "components-accordions",
        title: "Accordions",
        path: "/components/accordions",
        icon: "arrow_right",
      },
      {
        id: "components-badges",
        title: "Badges",
        path: "/components/badges",
        icon: "arrow_right",
      },
      {
        id: "components-buttons",
        title: "Buttons",
        path: "/components/buttons",
        icon: "arrow_right",
      },
      {
        id: "components-carousels",
        title: "Carousels",
        path: "/components/carousels",
        icon: "arrow_right",
      },
      {
        id: "components-media-objects",
        title: "Media Objects",
        path: "/components/media-objects",
        icon: "arrow_right",
      },
      {
        id: "components-modals",
        title: "Modals",
        path: "/components/modals",
        icon: "arrow_right",
      },
      {
        id: "components-navs-tabs",
        title: "Navs & Tabs",
        path: "/components/navs-tabs",
        icon: "arrow_right",
      },
      {
        id: "components-navbar",
        title: "Navbar",
        path: "/components/navbar",
        icon: "arrow_right",
      },
      {
        id: "components-pagination",
        title: "Pagination",
        path: "/components/pagination",
        icon: "arrow_right",
      },
      {
        id: "components-popovers-tooltips",
        title: "Popovers & Tooltips",
        path: "/components/popovers-tooltips",
        icon: "arrow_right",
      },
      {
        id: "components-progress",
        title: "Progress",
        path: "/components/progress",
        icon: "arrow_right",
      },
      {
        id: "components-spinners",
        title: "Spinners",
        path: "/components/spinners",
        icon: "arrow_right",
      },
      {
        id: "components-notifications",
        title: "Notifications",
        path: "/components/notifications",
        icon: "arrow_right",
      },
      {
        id: "components-avatars-chips",
        title: "Avatars & Chips",
        path: "/components/avatars-chips",
        icon: "arrow_right",
      },
      {
        id: "components-typography",
        title: "Typography",
        path: "/components/typography",
        icon: "arrow_right",
      },
      {
        id: "components-utilities",
        title: "Utilities",
        path: "/components/utilities",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "icons",
    title: "Icons",
    icon: "account_tree",
    children: [
      {
        id: "icons-line",
        title: "Line Icons",
        path: "/icons/line",
        icon: "arrow_right",
      },
      {
        id: "icons-boxicons",
        title: "Boxicons",
        path: "/icons/boxicons",
        icon: "arrow_right",
      },
      {
        id: "icons-feather",
        title: "Feather Icons",
        path: "/icons/feather",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "forms-tables-label",
    title: "Forms & Tables",
    icon: undefined,
    children: [],
  },
  {
    id: "forms",
    title: "Forms",
    icon: "toc",
    children: [
      {
        id: "forms-elements",
        title: "Form Elements",
        path: "/forms/elements",
        icon: "arrow_right",
      },
      {
        id: "forms-input-groups",
        title: "Input Groups",
        path: "/forms/input-groups",
        icon: "arrow_right",
      },
      {
        id: "forms-radios-checkboxes",
        title: "Radios & Checkboxes",
        path: "/forms/radios-checkboxes",
        icon: "arrow_right",
      },
      {
        id: "forms-layouts",
        title: "Forms Layouts",
        path: "/forms/layouts",
        icon: "arrow_right",
      },
      {
        id: "forms-validation",
        title: "Form Validation",
        path: "/forms/validation",
        icon: "arrow_right",
      },
      {
        id: "forms-wizard",
        title: "Form Wizard",
        path: "/forms/wizard",
        icon: "arrow_right",
      },
      {
        id: "forms-file-upload",
        title: "File Upload",
        path: "/forms/file-upload",
        icon: "arrow_right",
      },
      {
        id: "forms-date-pickers",
        title: "Date Pickers",
        path: "/forms/date-pickers",
        icon: "arrow_right",
      },
      {
        id: "forms-select2",
        title: "Select2",
        path: "/forms/select2",
        icon: "arrow_right",
      },
      {
        id: "forms-repeater",
        title: "Form Repeater",
        path: "/forms/repeater",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "tables",
    title: "Tables",
    icon: "api",
    children: [
      {
        id: "tables-basic",
        title: "Basic Table",
        path: "/tables/basic",
        icon: "arrow_right",
      },
      {
        id: "tables-datatable",
        title: "Data Table",
        path: "/tables/datatable",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "user-management-label",
    title: "User Management",
    icon: undefined,
    children: [],
  },
  {
    id: "device-management-label",
    title: "Device Management",
    icon: undefined,
    children: [],
  },
  {
    id: "beneficiaries-label",
    title: "Beneficiaries",
    icon: undefined,
    children: [],
  },
  {
    id: "pages-label",
    title: "Pages",
    icon: undefined,
    children: [],
  },
  {
    id: "authentication",
    title: "Authentication",
    icon: "lock",
    children: [
      {
        id: "auth-basic",
        title: "Basic",
        icon: "arrow_right",
        children: [
          {
            id: "auth-basic-login",
            title: "Login",
            path: "/auth/basic/login",
            icon: "arrow_right",
          },
          {
            id: "auth-basic-register",
            title: "Register",
            path: "/auth/basic/register",
            icon: "arrow_right",
          },
          {
            id: "auth-basic-forgot-password",
            title: "Forgot Password",
            path: "/auth/basic/forgot-password",
            icon: "arrow_right",
          },
          {
            id: "auth-basic-reset-password",
            title: "Reset Password",
            path: "/auth/basic/reset-password",
            icon: "arrow_right",
          },
        ],
      },
      {
        id: "auth-cover",
        title: "Cover",
        icon: "arrow_right",
        children: [
          {
            id: "auth-cover-login",
            title: "Login",
            path: "/auth/cover/login",
            icon: "arrow_right",
          },
          {
            id: "auth-cover-register",
            title: "Register",
            path: "/auth/cover/register",
            icon: "arrow_right",
          },
          {
            id: "auth-cover-forgot-password",
            title: "Forgot Password",
            path: "/auth/cover/forgot-password",
            icon: "arrow_right",
          },
          {
            id: "auth-cover-reset-password",
            title: "Reset Password",
            path: "/auth/cover/reset-password",
            icon: "arrow_right",
          },
        ],
      },
      {
        id: "auth-boxed",
        title: "Boxed",
        icon: "arrow_right",
        children: [
          {
            id: "auth-boxed-login",
            title: "Login",
            path: "/auth/boxed/login",
            icon: "arrow_right",
          },
          {
            id: "auth-boxed-register",
            title: "Register",
            path: "/auth/boxed/register",
            icon: "arrow_right",
          },
          {
            id: "auth-boxed-forgot-password",
            title: "Forgot Password",
            path: "/auth/boxed/forgot-password",
            icon: "arrow_right",
          },
          {
            id: "auth-boxed-reset-password",
            title: "Reset Password",
            path: "/auth/boxed/reset-password",
            icon: "arrow_right",
          },
        ],
      },
    ],
  },
  {
    id: "user-profile",
    title: "User Profile",
    icon: "account_circle",
    path: "/user-profile",
  },
  {
    id: "timeline",
    title: "Timeline",
    icon: "timeline",
    path: "/timeline",
  },
  {
    id: "pages",
    title: "Pages",
    icon: "description",
    children: [
      {
        id: "pages-404",
        title: "404 Error",
        path: "/pages/404",
        icon: "arrow_right",
      },
      {
        id: "pages-505",
        title: "505 Error",
        path: "/pages/505",
        icon: "arrow_right",
      },
      {
        id: "pages-coming-soon",
        title: "Coming Soon",
        path: "/pages/coming-soon",
        icon: "arrow_right",
      },
      {
        id: "pages-blank",
        title: "Blank Page",
        path: "/pages/blank",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "faq",
    title: "FAQ",
    icon: "help",
    path: "/faq",
  },
  {
    id: "pricing",
    title: "Pricing",
    icon: "payment",
    path: "/pricing",
  },
  {
    id: "charts-maps-label",
    title: "Charts & Maps",
    icon: undefined,
    children: [],
  },
  {
    id: "charts",
    title: "Charts",
    icon: "show_chart",
    children: [
      {
        id: "charts-apex",
        title: "Apex",
        path: "/charts/apex",
        icon: "arrow_right",
      },
      {
        id: "charts-chartjs",
        title: "Chartjs",
        path: "/charts/chartjs",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "maps",
    title: "Maps",
    icon: "map",
    children: [
      {
        id: "maps-google",
        title: "Google Maps",
        path: "/maps/google",
        icon: "arrow_right",
      },
      {
        id: "maps-vector",
        title: "Vector Maps",
        path: "/maps/vector",
        icon: "arrow_right",
      },
    ],
  },
  {
    id: "others-label",
    title: "Others",
    icon: undefined,
    children: [],
  },
  {
    id: "menu-levels",
    title: "Menu Levels",
    icon: "layers",
    children: [
      {
        id: "menu-level-1",
        title: "Level One",
        icon: "arrow_right",
        children: [
          {
            id: "menu-level-2",
            title: "Level Two",
            icon: "arrow_right",
            children: [
              {
                id: "menu-level-3",
                title: "Level Three",
                path: "/menu/level-three",
                icon: "arrow_right",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "documentation",
    title: "Documentation",
    icon: "description",
    path: "/documentation",
  },
  {
    id: "support",
    title: "Support",
    icon: "support",
    path: "/support",
  },
];
